# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PaDjrL1b85ZQVYMM1QR1X-z2FzFdQ0hm

Python script that takes two arguments: the path to a folder containing MP3 files and the path to the output folder for the converted WAV files. It uses the Pydub library to perform the conversion.
"""

import os
import sys
from pydub import AudioSegment

# Get the paths to the input and output folders from the command line arguments
mp3_folder = sys.argv[1]
wav_folder = sys.argv[2]

# Create the output folder if it doesn't exist
if not os.path.exists(wav_folder):
    os.makedirs(wav_folder)

# Loop over all the MP3 files in the input folder
for filename in os.listdir(mp3_folder):
    if filename.endswith(".mp3"):
        # Load the MP3 file and convert it to WAV
        mp3_path = os.path.join(mp3_folder, filename)
        sound = AudioSegment.from_mp3(mp3_path)
        wav_path = os.path.join(wav_folder, os.path.splitext(filename)[0] + ".wav")
        sound.export(wav_path, format="wav")

print("Conversion complete.")

"""save it as a Python file (e.g., mp3_to_wav.py) and run it from the command line, passing the path to the input folder and the output folder as arguments"""

python mp3_to_wav.py path/to/mp3/folder path/to/wav/folder

"""This will convert all the MP3 files in the input folder to WAV format and save them in the output folder.

You can modify the Python script I provided earlier to specify the destination folder where the WAV files are saved by changing the wav_folder variable to the desired path. Here's the modified script:
"""

import os
import sys
from pydub import AudioSegment

# Get the path to the input MP3 file from the command line argument
mp3_path = sys.argv[1]

# Get the destination folder for the WAV file from the command line argument
wav_folder = sys.argv[2]

# Create the destination folder if it doesn't exist
if not os.path.exists(wav_folder):
    os.makedirs(wav_folder)

# Load the MP3 file and convert it to WAV
sound = AudioSegment.from_mp3(mp3_path)
wav_path = os.path.join(wav_folder, os.path.splitext(os.path.basename(mp3_path))[0] + ".wav")
sound.export(wav_path, format="wav")

print("Conversion complete.")

"""To use this script, save it as a Python file (e.g., mp3_to_wav.py) and run it from the command line, passing the path to the input MP3 file and the destination folder for the WAV file as arguments."""

python mp3_to_wav.py path/to/input.mp3 path/to/destination/folder

"""This will convert the input MP3 file to WAV format and save it in the destination folder"""